version: "3.8"

services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golinksdb
      MYSQL_USER: user
      MYSQL_PASSWORD: temporary_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_service
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: temporary_password
      DB_NAME: golinksdb
    ports:
      - "8800:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:5173"

volumes:
  mysql_data:
